### ISSUE TITLE
abc_ic_menu_moreoverflow_mtrl_alpha resource not found on project import

### ISSUE THREAD

**Issue by thundergolfer** [architjn/Auro#14]
### Summary

After forking and importing Auro project to Android Studio, "@drawable/abc_ic_menu_moreoverflow_mtrl_alpha" resource cannot be found, resulting in build error.
### Steps
1. Fork Auro repo and leave as is
2. Open Android Studio and select Import existing project
3. Error pops up: "Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to .... "
4. Select option "Fix plugin version and sync project"
5. Gradle Sync Issue show up. "Gradle Version 2.10 is required, current version is 2.9..."
6. Select option "Fix Gradle Wrapper and re-import project"
7. Attempt to run project
### Expected Output

Project runs and app can be tested on connected Android debugging enabled device
### Actual Output

7-8 errors all to do with a missing resource

"No resource found that matches the given name(at 'src' with value '@drawable/abc_ic_menu_moreoverflow_mtrl_alpha')"
### Environment

Windows 10 Operating System
Android Studio 2.1.1
### Notes

The first to hang-ups on project import probably have little to do with actual resource error.
I apologise if this is an obvious fix on my end. I am new to Android development.
**This kind of problem is referenced in [this commit](https://github.com/spark/photon-tinker-android/commit/49459aeb1deeabbb0976ffdef667b3c0988a9e1f#commitcomment-17484267) on another Android app project.**

**Comment by creativetrendsapps** [comment]
This is actually not a drawable from this app it's from the Support library. Update the projects support, design and pallette libraries and re-build. This should resolve the issue. I had to do the same.

**Comment by boswelja** [comment]
My support:design and support:palette are up-to-date and I still have this problem :(

**Comment by boswelja** [comment]
@thundergolfer You can replace all of the erroring lines with this: `@drawable/abc_ic_menu_overflow_material`
